/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.primitive.JSUndefined;

public class ASTBlock extends SimpleNode implements Evalable {
	
	private boolean canReturn = false;
	
	public ASTBlock(int id) {
		super(id);
	}

	public ASTBlock(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		if( children == null ){
			return JSUndefined.getInstance();
		}
		
		registerFunctions(env);
		
		Object lastValue = null;
		for (int i = 0; i < children.length; i++) {
			if( env.isReturnCalled() ){
				break;
			}
			Node child = children[i];
			if( child instanceof ASTFunctionDeclaration){
				continue; //should be already registered
			}
			lastValue = ((Evalable) child).evalIn(env);
		}
		if( env.isReturnCalled() && canReturn ){
			env.setReturnCalled(false);
			return env.getReturnValue();
		}
		return lastValue;
	}

	private void registerFunctions(JSEnvironment env) {
		for (int i = 0; i < children.length; i++) {
			Node child = children[i];
			if( child instanceof ASTFunctionDeclaration){
				((Evalable) child).evalIn(env);
			}
		}
	}

	public boolean isCanReturn() {
		return canReturn;
	}

	public void setCanReturn(boolean canReturn) {
		this.canReturn = canReturn;
	}
}
/* JavaCC - OriginalChecksum=1031df234569a702c87b767ecea62329 (do not edit this line) */
