/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.primitive.JSUndefined;
import cz.fit.cvut.paskaond.jsruntime.syntax.CastUtils;

/*
	ForStatement
		AssignmentExpression
			Identifier[i]
			Operator
			NumberLiteral[1]
		BinaryExpressionSequence
			Identifier[i]
			Operator
			NumberLiteral[4]
		PostfixExpression
			Identifier[i]
			Operator
		Block
 * 
 */


public class ASTForStatement extends SimpleNode implements Evalable{
	public ASTForStatement(int id) {
		super(id);
	}

	public ASTForStatement(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		Evalable ch0 = (Evalable) children[0];
		ch0.evalIn(env);	
		Evalable ch1 = (Evalable) children[1];
		Evalable ch2 = (Evalable) children[2];
		Evalable ch3 = (Evalable) children[3];
		while(true){
			if( env.isBreakCalled() ){
				env.setBreakCalled(false);
				break;
			}
			if( env.isReturnCalled() ){
				if( this instanceof ASTForVarStatement){
					env.getParent().setReturnValue( env.getReturnValue() );
				}
				break;
			}
			Object conditionResult = ch1.evalIn(env);
			if( CastUtils.castToBoolean(conditionResult) == true ){
				ch3.evalIn(env);
			}else{
				break;
			}
			ch2.evalIn(env);
		}
		
		return JSUndefined.getInstance();
	}
}
/* JavaCC - OriginalChecksum=9a88965631e91ce2619e40442643cc48 (do not edit this line) */
