/* Generated By:JJTree: Do not edit this line. ASTFunctionCallParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import java.util.List;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.primitive.JSUndefined;
import cz.fit.cvut.paskaond.jsruntime.exception.TooManyArgumentsException;

/*
 * FunctionCallParameters
				StringLiteral[Hello ]
 */
public class ASTFunctionCallParameters extends SimpleNode implements Evalable {
	public ASTFunctionCallParameters(int id) {
		super(id);
	}

	public ASTFunctionCallParameters(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		// TODO Auto-generated method stub
		return null;
	}

	public void evalToEnv(List<String> formals, JSEnvironment context, JSEnvironment pushTo) {
		
		if( tooManyArgs(formals) ){			
			throw new TooManyArgumentsException("Too many arguments for function. Expected:"+
					(formals == null ? 0 : formals.size())+", Got:"+
					(children == null ? 0 : children.length));
		}
		
		if( formals == null){
			return;
		}
		
		//Add parameters to context
		int i;
		for (i = 0; children != null && i < children.length; i++) {
			pushTo.put(formals.get(i), ((Evalable) children[i]).evalIn(context)) ;
		}
		// put missing args as undefined
		while( i < formals.size()){
			pushTo.put(formals.get(i), JSUndefined.getInstance()) ;
			i++;
		}
	}

	private boolean tooManyArgs(List<String> formals) {
		if( formals == null && children != null && children.length > 0 ){
			return true;
		}
		if( formals != null && children != null && children.length > formals.size()){
			return true;
		}
		return false;
	}
}
/* JavaCC - OriginalChecksum=c0d47b7a233d393f304a61efdd597a68 (do not edit this line) */
