/* Generated By:JJTree: Do not edit this line. ASTForVarStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;

/*
 *  * 	ForVarStatement
		VariableDeclaration
			Identifier[i]
			NumberLiteral[1]
		BinaryExpressionSequence
			Identifier[i]
			Operator
			NumberLiteral[4]
		PostfixExpression
			Identifier[i]
			Operator
		Block
 * 
 */

public class ASTForVarStatement extends ASTForStatement implements Evalable{
	public ASTForVarStatement(int id) {
		super(id);
	}

	public ASTForVarStatement(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		JSEnvironment newEnv = new JSEnvironment(env);
		return super.evalIn(newEnv);
	}
}
/* JavaCC - OriginalChecksum=50da72fcb1b3cd41e84bdca5f1a8e532 (do not edit this line) */
