/* Generated By:JJTree: Do not edit this line. ASTLiteralField.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;

public
class ASTLiteralField extends SimpleNode {
	public ASTLiteralField(int id) {
		super(id);
	}

	public ASTLiteralField(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String getName(){
		ASTIdentifier ident = ((ASTIdentifier) children[0]);
		return ident.getName();
	}

	public Object getValue(JSEnvironment env){
		return ((Evalable)children[1]).evalIn(env);
	}

}
/* JavaCC - OriginalChecksum=4704bcfe987770a79ac78425c8372e94 (do not edit this line) */
