/* Generated By:JJTree: Do not edit this line. ASTPropertyValueReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;

public class ASTPropertyValueReference extends SimpleNode implements Evalable{
	public ASTPropertyValueReference(int id) {
		super(id);
	}

	public ASTPropertyValueReference(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		return ((Evalable) children[0]).evalIn(env);
	}
}
/* JavaCC - OriginalChecksum=c9dfb7136bcf40dd5612ea222f7bbaac (do not edit this line) */
