/* Generated By:JJTree: Do not edit this line. ASTParenExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;

public class ASTParenExpression extends SimpleNode implements Evalable {
	public ASTParenExpression(int id) {
		super(id);
	}

	public ASTParenExpression(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		if( children.length > 1 ){
			throw new RuntimeException("Not implemented yet");
		} 
		return ((Evalable) children[0]).evalIn(env);
	}
}
/* JavaCC - OriginalChecksum=5f03e2a997ce33a17d566387beb2e74f (do not edit this line) */
