/* Generated By:JJTree: Do not edit this line. ASTPropertyIdentifierReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;

public class ASTPropertyIdentifierReference extends SimpleNode implements Evalable {

	public ASTPropertyIdentifierReference(int id) {
		super(id);
	}

	public ASTPropertyIdentifierReference(EcmaScript p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		ASTIdentifier child = (ASTIdentifier) children[0];
		return child.getName(); //do not eval here;
	}

}
/* JavaCC - OriginalChecksum=965c18624da7e23adf23b2cf9708851a (do not edit this line) */
