/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.primitive.JSUndefined;

/*
 * 
 * 		ReturnStatement
		BinaryExpressionSequence
			Identifier[arg1]
			Operator
			StringLiteral[World]
 *
 */

public class ASTReturnStatement extends SimpleNode implements Evalable {
	public ASTReturnStatement(int id) {
		super(id);
	}

	public ASTReturnStatement(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		Object value = null;
		if(children != null && children.length > 0 ){
			value = ((Evalable) children[0]).evalIn(env);
		}else{
			value = JSUndefined.getInstance();
		}
		env.setReturnValue(value);
		return value;
	}
}
/* JavaCC - OriginalChecksum=5596808c05b9bbd1f21f7946c67fed8c (do not edit this line) */
