/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.operators.JSBinaryOperator;

public class ASTUnaryExpression extends SimpleNode implements Evalable{
	public ASTUnaryExpression(int id) {
		super(id);
	}

	public ASTUnaryExpression(EcmaScript p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		ASTOperator op = (ASTOperator) children[0];
		JSBinaryOperator opFunc = (JSBinaryOperator) env.get(op.getType());
		Object value = ((Evalable) children[1]).evalIn(env); 
		return opFunc.call( 0,value );
	}
}
/* JavaCC - OriginalChecksum=b7deb6417a782273bf8eb126a8d4d615 (do not edit this line) */
