/* Generated By:JJTree: Do not edit this line. ASTVariableStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser;

import cz.fit.cvut.paskaond.jsruntime.Evalable;
import cz.fit.cvut.paskaond.jsruntime.JSEnvironment;
import cz.fit.cvut.paskaond.jsruntime.builtin.JSStatement;

/*
 * 	VariableStatement
		VariableDeclaration
			Identifier[a]
			Literal[5]
 * 
 */
public class ASTVariableStatement extends JSStatement {
	public ASTVariableStatement(int id) {
		super(id);
	}

	public ASTVariableStatement(EcmaScript p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public Object evalIn(JSEnvironment env) {
		return ((Evalable) children[0]).evalIn(env);
	}
}
/* JavaCC - OriginalChecksum=b2ee7936d0b9801a548c75bc92aab4bf (do not edit this line) */
